
spring:
  application:
    name: dubbo-demo-consumer
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    #web-application-type: none
dubbo:
  scan:
    base-packages: com.eric.dubbo.consumer
  registry:
    address: zookeeper://172.16.210.151:2181,172.16.210.152:2181,172.16.210.153:2181
  metadata-report:
    address: zookeeper://172.16.210.151:2181,172.16.210.152:2181,172.16.210.153:2181