
spring:
  application:
    name: dubbo-demo-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  scan:
    base-packages: com.com.eric.dubbo.consumer
  registry:
    address: zookeeper://172.16.210.141:2181,172.16.210.142:2181,172.16.210.143:2181
  metadata-report:
    address: zookeeper://172.16.210.141:2181,172.16.210.142:2181,172.16.210.143:2181